using Resonance.Systems.Waves;

namespace Resonance.Systems.Waves.Editors
{
    /// <summary>
    /// Interface for objects that can output waves generated by the modular editor
    /// Implemented by WaveGun, CrystalCore, Diffuser, etc.
    /// Allows these objects to receive and use waves from the module graph
    /// </summary>
    public interface IWaveOutput
    {
        /// <summary>
        /// Set the output wave from the module graph
        /// Called when the module graph is executed and generates a final wave
        /// </summary>
        /// <param name="wave">The generated wave from the module graph</param>
        void SetOutputWave(Wave wave);
        
        /// <summary>
        /// Get the current output wave
        /// </summary>
        Wave GetOutputWave();
        
        /// <summary>
        /// Check if this output is ready to receive waves
        /// </summary>
        bool IsReady { get; }
        
        /// <summary>
        /// Validate the output wave (check for extreme states, etc.)
        /// </summary>
        bool ValidateWave(Wave wave);
    }
}

